version: '3'

services:
  worker:
    environment:
      # configure a network range that doesn't overlap with the outer worker
      CONCOURSE_GARDEN_NETWORK_POOL: '10.224.0.0/16'

      # prevent worker from dropping out if the outer worker is overloaded
      CONCOURSE_EPHEMERAL: 'false'
